export * from '@/domain/use-cases/errors/email-already-in-use';
export * from '@/domain/use-cases/errors/phone-already-in-use';
export * from '@/domain/use-cases/errors/document-already-in-use';
export * from '@/domain/use-cases/errors/user-not-found';
export * from '@/domain/use-cases/errors/restaurateur-not-found';
export * from '@/domain/use-cases/errors/invalid-credentials';
export * from '@/domain/use-cases/errors/establishment-not-found';
export * from '@/domain/use-cases/errors/location-already-in-use';
export * from '@/domain/use-cases/errors/postal-code-already-in-use';
